[package]
name = "cw-2-rs"
version = "0.1.0"
authors = ["Joshua Coles <josh@coles.to>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

array2d = "0.2.1"
rand = "0.8.3"
maplit = "1.0.2"
